name: 义诊室监控
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: pip install requests
      - run: python watch.py
        env:
          SCKEY: ${{ secrets.SCKEY }}
